// Code generated by GoVPP's binapi-generator. DO NOT EDIT.

package osvbng_l2gw

import (
	"context"
	"fmt"
	"io"

	memclnt "github.com/veesix-networks/osvbng/pkg/vpp/binapi/memclnt"
	api "go.fd.io/govpp/api"
)

// RPCService defines RPC service osvbng_l2gw.
type RPCService interface {
	OsvbngL2gwAddDelCircuit(ctx context.Context, in *OsvbngL2gwAddDelCircuit) (*OsvbngL2gwAddDelCircuitReply, error)
	OsvbngL2gwCircuitDump(ctx context.Context, in *OsvbngL2gwCircuitDump) (RPCService_OsvbngL2gwCircuitDumpClient, error)
	OsvbngL2gwCircuitSetState(ctx context.Context, in *OsvbngL2gwCircuitSetState) (*OsvbngL2gwCircuitSetStateReply, error)
	OsvbngL2gwEnableDisable(ctx context.Context, in *OsvbngL2gwEnableDisable) (*OsvbngL2gwEnableDisableReply, error)
}

type serviceClient struct {
	conn api.Connection
}

func NewServiceClient(conn api.Connection) RPCService {
	return &serviceClient{conn}
}

func (c *serviceClient) OsvbngL2gwAddDelCircuit(ctx context.Context, in *OsvbngL2gwAddDelCircuit) (*OsvbngL2gwAddDelCircuitReply, error) {
	out := new(OsvbngL2gwAddDelCircuitReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) OsvbngL2gwCircuitDump(ctx context.Context, in *OsvbngL2gwCircuitDump) (RPCService_OsvbngL2gwCircuitDumpClient, error) {
	stream, err := c.conn.NewStream(ctx)
	if err != nil {
		return nil, err
	}
	x := &serviceClient_OsvbngL2gwCircuitDumpClient{stream}
	if err := x.Stream.SendMsg(in); err != nil {
		return nil, err
	}
	if err = x.Stream.SendMsg(&memclnt.ControlPing{}); err != nil {
		return nil, err
	}
	return x, nil
}

type RPCService_OsvbngL2gwCircuitDumpClient interface {
	Recv() (*OsvbngL2gwCircuitDetails, error)
	api.Stream
}

type serviceClient_OsvbngL2gwCircuitDumpClient struct {
	api.Stream
}

func (c *serviceClient_OsvbngL2gwCircuitDumpClient) Recv() (*OsvbngL2gwCircuitDetails, error) {
	msg, err := c.Stream.RecvMsg()
	if err != nil {
		return nil, err
	}
	switch m := msg.(type) {
	case *OsvbngL2gwCircuitDetails:
		return m, nil
	case *memclnt.ControlPingReply:
		err = c.Stream.Close()
		if err != nil {
			return nil, err
		}
		return nil, io.EOF
	default:
		return nil, fmt.Errorf("unexpected message: %T %v", m, m)
	}
}

func (c *serviceClient) OsvbngL2gwCircuitSetState(ctx context.Context, in *OsvbngL2gwCircuitSetState) (*OsvbngL2gwCircuitSetStateReply, error) {
	out := new(OsvbngL2gwCircuitSetStateReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) OsvbngL2gwEnableDisable(ctx context.Context, in *OsvbngL2gwEnableDisable) (*OsvbngL2gwEnableDisableReply, error) {
	out := new(OsvbngL2gwEnableDisableReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}
